"""empty message

Revision ID: 2a91e20252d9
Revises: c10c2ed73ddf
Create Date: 2022-08-11 20:57:41.019461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a91e20252d9'
down_revision = 'c10c2ed73ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('artists', 'no_upcoming_shows')
    op.drop_column('artists', 'no_past_shows')
    op.alter_column('venues', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('venues', 'no_upcoming_shows')
    op.drop_column('venues', 'no_past_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('no_past_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('no_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('venues', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.add_column('artists', sa.Column('no_past_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('no_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('artists', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
