"""empty message

Revision ID: c10c2ed73ddf
Revises: dfd6e28f5df3
Create Date: 2022-08-11 15:26:13.676655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10c2ed73ddf'
down_revision = 'dfd6e28f5df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('no_past_shows', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('no_past_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'no_past_shows')
    op.drop_column('artists', 'no_past_shows')
    # ### end Alembic commands ###
